### ISSUE TITLE
Process metrics: Track renames 

### ISSUE THREAD

**Issue by mauricioaniche** [mauricioaniche/predicting-refactoring-ml#19]
For now, we are not properly tracking renames. So, when a file is renamed, the new file has all its process metrics starting from zero again.

Keep a track of renames, so that we can "transfer" the number from the old files to the new files.

**Comment by jan-gerling** [comment]
I will work on this issue on this branch [feature/TrackRenames](https://github.com/mauricioaniche/predicting-refactoring-ml/tree/feature/TrackRenames).

**Comment by jan-gerling** [comment]
Currently, we are using filenames instead of class names in order to reference process metrics of classes. Is this intended?

**Comment by jan-gerling** [comment]
I found that we currently only use **filenames instead of classnames** to track process metrics in the `PMDatabase.java`. Thus, we use the same process metric for all classes in a file.

@mauricioaniche Is there a way to get and track process metrics for classes only? So far, I could not come up with a way to get process metrics with jgit, but separate them per class.
